// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

using NUnit.Framework;
using Shouldly;

namespace DataImport.Common.Tests
{
    [TestFixture]
    internal class EncryptionTests
    {
        [Test]
        public void Encrypt_then_Decrypt_roundtrips_plaintext()
        {
            const string plainText = "sensitive-credential-value";
            const string key = "test-encryption-key-32-chars-min!";

            var cipherText = Encryption.Encrypt(plainText, key);
            var result = Encryption.Decrypt(cipherText, key);

            result.ShouldBe(plainText);
        }

        [Test]
        public void Decrypt_handles_existing_ciphertext()
        {
            // Known ciphertext produced by Rijndael256 3.2.0 RijndaelEtM.Encrypt with
            //   plainText = "existing-value", key = "my-key", IV = 0x00...00 (16 zero bytes).
            // Generated by replicating the exact Rijndael256 key-derivation + AES-256-CBC
            // algorithm in Python (hashlib.pbkdf2_hmac SHA-1 + openssl enc -aes-256-cbc)
            // before the Rijndael256 package was removed from the project.
            // Wire format: Base64(iv[16] + aes_cbc_body + pbkdf2_sha1_mac[64])
            const string key = "my-key";
            const string knownCipherText =
                "AAAAAAAAAAAAAAAAAAAAAKulZn3RuEnnTcHh4YsaZ+HFRJwLK7DWqOW4zjQR6H2RegucRvfTYCaMGnSTCFJKJewi0cRwUj2ruXw1vxCAc/Muhk9uc32xEf+RxmiJNVmv";
            const string expectedPlainText = "existing-value";

            var result = Encryption.Decrypt(knownCipherText, key);

            result.ShouldBe(expectedPlainText);
        }
    }
}
