# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Publish Installer Pre-release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_VERSION: ${{ secrets.SEMANTIC_VERSION }}
  API_KEY: ${{ secrets.AZURE_ARTIFACTS_PAT }}
  AZURE_ARTIFACTS_FEED_URL: ${{ secrets.AZURE_ARTIFACTS_FEED_URL }}  
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint": "${{ secrets.AZURE_ARTIFACTS_FEED_URL }}","password": "${{ secrets.AZURE_ARTIFACTS_PAT }}"}]}'

jobs:
  create-and-publish-installer-pre-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
    - name: Setup .NET
      uses: actions/setup-dotnet@499789684c9a0d41c9b3f0d66a785ba17b1d51ab # v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Install-credential-handler
      run: iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"
      shell: pwsh
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1 #v1.0.5
    - name: Build-and-publish-package
      run: ./Installer/build-and-publish-package.ps1 -SemanticVersion ${{ env.BUILD_VERSION }} -BuildCounter ${{ github.run_number }} -NuGetFeed ${{env.AZURE_ARTIFACTS_FEED_URL}} -PublishPreRelease -NuGetApiKey  ${{ env.API_KEY }}
      shell: pwsh
